const rand = (max, min = 0) => Math.floor(Math.random() * (max - min + 1)) + min

export const FLIGHTS = [
    {
        id: 0,
        name: 'Air India',
        number: 'AI 537',
        image: '',
        category: 'Non Stop',
        duration:  '2h 10m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '09:55',
        reachTime: '12:05',
        featured: true,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
    },
    {
        id: 1,
        name: 'Vistara',
        number: 'UK 995',
        image: '',
        category: 'Non Stop',
        duration: '2h 25m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '14:35',
        reachTime: '17:00',
        featured: false,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
    },
    {
        id: 2,
        name: 'Indigo',
        number: '6E 5339',
        image: '',
        category: 'Non Stop',
        duration: '1h 35m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '17:00',
        reachTime: '18:35',
        featured: false,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
    },
    {
        id: 3,
        name: 'SpiceJet',
        number: 'SG 8723',
        image: '',
        category: 'Non Stop',
        duration: '4h 35m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '19:00',
        reachTime: '23:35',
        featured: false,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
    },
    {
        id: 4,
        name: 'Go Air',
        number: 'G8 339',
        image: '',
        category: 'Non Stop',
        duration: '1h 55m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '19:00',
        reachTime: '21:55',
        featured: false,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`, 
       },
    {
        id: 5,
        name: 'Air India',
        number: 'AI 537',
        image: '',
        category: 'Non Stop',
        duration:  '2h 10m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '09:55',
        reachTime: '12:05',
        featured: true,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
        },
    {
        id: 6,
        name: 'Vistara',
        number: 'UK 995',
        image: '',
        category: 'Non Stop',
        duration: '2h 25m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '14:35',
        reachTime: '17:00',
        featured: false,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
        },
    {
        id: 7,
        name: 'Indigo',
        number: '6E 5339',
        image: '',
        category: 'Non Stop',
        duration: '1h 35m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '17:00',
        reachTime: '18:35',
        featured: false,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
        },
    {
        id: 8,
        name: 'SpiceJet',
        number: 'SG 8723',
        image: '',
        category: 'Non Stop',
        duration: '4h 35m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '19:00',
        reachTime: '23:35',
        featured: false,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
        },
    {
        id: 9,
        name: 'Go Air',
        number: 'G8 339',
        image: '',
        category: 'Non Stop',
        duration: '1h 55m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '19:00',
        reachTime: '21:55',
        featured: false,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
        },
    {
        id: 10,
        name: 'Air India',
        number: 'AI 537',
        image: '',
        category: 'Non Stop',
        duration:  '2h 10m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '09:55',
        reachTime: '12:05',
        featured: true,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
        },
    {
        id: 11,
        name: 'Vistara',
        number: 'UK 995',
        image: '',
        category: 'Non Stop',
        duration: '2h 25m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '14:35',
        reachTime: '17:00',
        featured: false,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
        },
    {
        id: 12,
        name: 'Indigo',
        number: '6E 5339',
        image: '',
        category: 'Non Stop',
        duration: '1h 35m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '17:00',
        reachTime: '18:35',
        featured: false,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
        },
    {
        id: 13,
        name: 'SpiceJet',
        number: 'SG 8723',
        image: '',
        category: 'Non Stop',
        duration: '4h 35m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '19:00',
        reachTime: '23:35',
        featured: false,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,
        },
    {
        id: 14,
        name: 'Go Air',
        number: 'G8 339',
        image: '',
        category: 'Non Stop',
        duration: '1h 55m',
        price: `${rand(9,2)}${rand(990,100)}`,
        departTime: '19:00',
        reachTime: '21:55',
        featured: false,
        originAirport: 'Indira Gandhi International Airport',
        destinationAirport: 'Chattrapati shivaji International Airport',
        terminal: `${rand(6,1)}`,
        terminal1: `${rand(6,1)}`,     
    },
]
